MVCBoutik/Areas/Boutik/Models/Ligne.cs
using AdopteUneDev.DAL;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace MVCBoutik.Areas.Boutik.Models
{
    public class Ligne
    {

        private Developer _zeDave;
        private int _qte;
        private int _choix;
        private DateTime _dateDebut;

        public Developer ZeDave
        {
            get { return _zeDave; }
            set { _zeDave = value; }
        }
        public int Qte
        {
            get { return _qte; }
            set { _qte = value; }
        }
        public int Choix
        {
            get { return _choix; }
            set { _choix = value; }
        }
        public DateTime DateDebut
        {
            get { return _dateDebut; }
            set { _dateDebut = value; }
        }
    
    }
}

MVCBoutik/Areas/Boutik/Controllers/PanierController.cs
using AdopteUneDev.DAL;
using MVCBoutik.Areas.Boutik.Models;
using MVCBoutik.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVCBoutik.Areas.Boutik.Controllers
{
    public class PanierController : Controller
    {
        //
        // Renvoi la vue AddToBasket (même vide car ne nécessite pas de paramètres) 
        // Action renseignée pour les liens dans le layout et la vue index
        public ActionResult Index()
        {
            return View("AddToBasket", SessionTools.Panier);
        }

        //Envoi les information pour créer une nouvelle ligne
        [HttpPost]
        public ActionResult AddToBasket(int dev, int qte, int choix, DateTime dateDebut)
        {
            //if (SessionTools.Login == null)
            //{
            //    return RedirectToRoute(new { controller = "Home", action = "Index", area = "" });
            //}
            //else
            //{
                if (qte < 1) // pour ne pas avoir un prix négatif
                {
                    return RedirectToRoute(new { controller = "Home", action = "Index", area = "" });
                }
                else
                {
                    Developer d = Developer.ChargerUnDev(dev);
                    if (SessionTools.Panier.Lignes.Where(li => li.ZeDave.IdDev == dev).Count() > 0) //vérifie si le déveloper est déjà dans le panier
                    {
                        return RedirectToRoute(new { controller = "Home", action = "Index", area = "" }); //si oui, on ne peux pas l'ajouter!
                    }
                    Ligne l = new Ligne() { ZeDave = d, Qte = qte, Choix = choix, DateDebut = dateDebut };
                    SessionTools.Panier.Lignes.Add(l);
                }
                return View("AddToBasket", SessionTools.Panier);

            }
        //}

        // permet d'augmenter ou de diminuer la quantité
        //booleen déclarer à true pour le plus et à false pour le - dans la vue partielle _Ligne
        [HttpGet]
        public ActionResult AddToBasket(int id, int qte, bool op)
        {

            if (SessionTools.Panier.Lignes.Where(li => li.ZeDave.IdDev == id).Count() > 0) // vérifie qu'il y a un developer
            {
                if (op) // si le booléen 
                {
                    SessionTools.Panier.Lignes.Where(li => li.ZeDave.IdDev == id).FirstOrDefault().Qte += qte;
                }
                else
                {
                    SessionTools.Panier.Lignes.Where(li => li.ZeDave.IdDev == id).FirstOrDefault().Qte -= qte;
                }
                if (SessionTools.Panier.Lignes.Where(li => li.ZeDave.IdDev == id).FirstOrDefault().Qte < 1) SessionTools.Panier.Lignes.Remove(SessionTools.Panier.Lignes.Where(li => li.ZeDave.IdDev == id).FirstOrDefault());
            }
            return View("AddToBasket", SessionTools.Panier);
        }

        [HttpPost]
        public ActionResult SupLigne(int id)
        {
            Ligne c = null; 
            foreach (Ligne e in SessionTools.Panier.Lignes)
            {
                if (e.ZeDave.IdDev == id)
                {
                    c = e;
                }
            }
            SessionTools.Panier.Lignes.Remove(c);
            //Equivalent du foreach ci-dessus => SessionTools.Panier.Remove(SessionTools.Panier.Lignes.Where(e=>e.ZeDave.IdDev==id).Single());
            return View("AddToBasket", SessionTools.Panier);
        }

        public ActionResult ConfirmerPanier()
        {
            if (SessionTools.Login == null)
            {
                return RedirectToRoute(new { controller = "Client", action = "SeLogger", area = "Membre" });
            }
            else 
            {
                panierClient p = new panierClient()
                {
                    ClientCourant = SessionTools.client,
                    PanierCourant = SessionTools.Panier,
                };
               return View(p);
            }
            
        }
	}
}

MVCBoutik/Areas/Boutik/Views/Shared/_ConfirmeLigne.cshtml
@model MVCBoutik.Areas.Boutik.Models.Ligne
<tr>
    <td class="cart_product">
        <a href="">
            <img src="~/content/images/home/@Model.ZeDave.DevPicture" alt="" style="width:80px;" />
        </a>
    </td>
    <td class="cart_description">
        <h4><a href="">@Model.ZeDave.DevFirstName @Model.ZeDave.DevName</a></h4>
        <p>@Model.ZeDave.NomCategPrincipal</p>
    </td>
    <td class="cart_price">
        @{
            if (Model.Choix == Model.ZeDave.DevHourCost)
            {
                <p>@Model.ZeDave.DevHourCost €/heure</p>
            }
            else if (Model.Choix == Model.ZeDave.DevDayCost)
            {
                <p>@Model.ZeDave.DevDayCost €/jour</p>
            }
            else
            {
                <p>@Model.ZeDave.DevMonthCost €/mois</p>
            }
        }
    </td>
    <td class="cart_quantity">
            <p>@Model.Qte</p>
        
    </td>
    <td>
        <p>@Model.DateDebut.ToShortDateString()</p>
    </td>
    <td class="cart_total">
        <p class="cart_total_price">
            @{
                int price = (int)Model.Qte * (int)Model.Choix;
            }
            @price €
    </td>
</tr>

MVCBoutik/Areas/Boutik/Views/Shared/_Ligne.cshtml
@model MVCBoutik.Areas.Boutik.Models.Ligne
<tr>
<td class="cart_product">
    <a href="">
        <img src="~/content/images/home/@Model.ZeDave.DevPicture" alt="" style="width:80px;" />
    </a>
</td>
<td class="cart_description">
    <h4><a href="">@Model.ZeDave.DevFirstName @Model.ZeDave.DevName</a></h4>
    <p>@Model.ZeDave.NomCategPrincipal</p>
</td>
<td class="cart_price">
    @{
        if (Model.Choix == Model.ZeDave.DevHourCost)
      {
               <p>@Model.ZeDave.DevHourCost €/heure</p>
      }
        else if (Model.Choix == Model.ZeDave.DevDayCost)
      {
                <p>@Model.ZeDave.DevDayCost €/jour</p>
      }
      else
      {
                <p>@Model.ZeDave.DevMonthCost €/mois</p> 
      }
          }
</td>
<td class="cart_quantity">
    <div class="cart_quantity_button">
        @Html.ActionLink("+", "AddToBasket", "Panier", new { area = "Boutik", id= @Model.ZeDave.IdDev, qte = 1, op = true }, null)
        <input class="cart_quantity_input" type="text" name="quantity" value="@Model.Qte" autocomplete="off" size="2">
        @Html.ActionLink("-", "AddToBasket", "Panier", new { area = "Boutik", id = @Model.ZeDave.IdDev, qte = 1, op = false }, null)
    </div>
</td>
    <td>
        <p>@Model.DateDebut.ToShortDateString() </p>
    </td>
<td class="cart_total">
    <p class="cart_total_price">
    @{ 
        int price;
        if (Model.Choix == Model.ZeDave.DevHourCost)
      {

          price = (int)Model.Qte * (int)Model.ZeDave.DevHourCost;
      }
        else if (Model.Choix == Model.ZeDave.DevDayCost)
      {
          price = (int)Model.Qte * (int)Model.ZeDave.DevDayCost;
      }
      else
      {
          price = (int)Model.Qte * (int)Model.ZeDave.DevMonthCost;
      }
    } 
        @price €
</td>
<td class="cart_delete">
    <form method="post" action="~/Boutik/Panier/SupLigne" class="cart_quantity_delete">
        <input type="hidden" value="@Model.ZeDave.IdDev" name="id"/>
        <input type="submit" value="delete"/>
    </form>
</td>
    </tr>